<?php

namespace Database\Factories;

use App\Models\Book;
use App\Models\Author;
use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

class BookFactory extends Factory
{
    protected $model = Book::class;

    public function definition(): array
    {
        $fantasyTitles = [
            'A Game of Thrones',
            'A Clash of Kings',
            'A Storm of Swords',
            'A Feast for Crows',
            'A Dance with Dragons',
            'The Name of the Wind',
            'The Wise Man\'s Fear',
            'The Way of Kings',
            'Words of Radiance',
            'Oathbringer',
            'The Hobbit',
            'The Lord of the Rings',
            'The Eye of the World',
            'The Great Hunt',
            'The Dragon Reborn',
            'Mistborn: The Final Empire',
            'The Well of Ascension',
            'The Hero of Ages',
            'The Blade Itself',
            'Before They Are Hanged',
            'The Last Argument of Kings',
            'The Lies of Locke Lamora',
            'Red Seas Under Red Skies',
            'The Republic of Thieves',
            'The Black Prism',
            'The Broken Eye',
            'The Burning White',
            'The Priory of the Orange Tree',
            'The Poppy War',
            'The Bone Season',
            'To Kill a Mockingbird',
            '1984',
            'Pride and Prejudice',
            'The Great Gatsby',
            'Moby Dick',
            'War and Peace',
            'The Catcher in the Rye',
            'The Da Vinci Code',
            'The Alchemist',
            'The Hunger Games',
            'Harry Potter and the Sorcerer\'s Stone',
            'Harry Potter and the Chamber of Secrets',
            'Harry Potter and the Prisoner of Azkaban',
            'Harry Potter and the Goblet of Fire',
            'Harry Potter and the Order of the Phoenix',
            'Harry Potter and the Half-Blood Prince',
            'Harry Potter and the Deathly Hallows',
            'The Fault in Our Stars',
            'Gone Girl',
            'The Girl with the Dragon Tattoo',
            'The Kite Runner',
            'Life of Pi',
            'The Book Thief',
            'The Road',
            'The Shining',
            'Dracula',
            'Frankenstein',
            'The Handmaid\'s Tale',
            'Brave New World',
            'The Giver',
            'The Outsiders',
            'Little Women',
            'Anne of Green Gables',
            'Charlotte\'s Web',
            'Matilda',
            'The Very Hungry Caterpillar',
            'Where the Wild Things Are',
            'The Cat in the Hat',
            'The Secret Garden',
            'Wuthering Heights',
            'Jane Eyre',
            'Crime and Punishment',
            'The Brothers Karamazov',
            'Don Quixote',
            'Les Misérables',
            'The Count of Monte Cristo',
            'The Little Prince',
            'The Old Man and the Sea',
            'The Sun Also Rises',
            'A Tale of Two Cities',
            'Great Expectations',
            'David Copperfield',
            'Oliver Twist',
            'The Picture of Dorian Gray',
            'Dr. Jekyll and Mr. Hyde',
            'Treasure Island',
            'Robinson Crusoe',
            'Gulliver\'s Travels',
            'Fahrenheit 451',
            'Slaughterhouse-Five',
            'Catch-22',
            'Lolita',
            'Ulysses',
            'The Grapes of Wrath',
            'East of Eden',
            'Of Mice and Men',
            'The Call of the Wild',
            'White Fang',
            'Watership Down',
            'Animal Farm',
            'Lord of the Flies',
            'The Wind in the Willows',
            'The Jungle Book',
            'Peter Pan',
            'The Tale of Peter Rabbit',
            'Winnie-the-Pooh',
            'The Velveteen Rabbit',
            'Goodnight Moon',
            'The Giving Tree',
            'Where the Red Fern Grows',
            'Old Yeller',
            'The Secret Life of Bees',
            'Memoirs of a Geisha',
            'The Lovely Bones',
            'The Help',
            'Room',
            'The Girl on the Train',
            'Big Little Lies',
            'The Goldfinch',
            'The Night Circus',
            'The Shadow of the Wind',
            'The Thirteenth Tale',
            'The Light Between Oceans',
            'All the Light We Cannot See',
            'The Guernsey Literary and Potato Peel Pie Society',
            'The Immortal Life of Henrietta Lacks',
            'Educated',
            'Becoming',
            'Wild',
            'Unbroken',
            'Into the Wild',
            'The Glass Castle',
            'Angela\'s Ashes',
            'The Devil in the White City',
            'In Cold Blood',
            'The Wright Brothers',
            'Steve Jobs',
            'The Diary of a Young Girl',
            'Night',
            'Man\'s Search for Meaning',
            'Sapiens',
            'Thinking, Fast and Slow',
            'The Power of Habit',
            'Outliers',
            'The Tipping Point',
            'Quiet',
            'Grit',
            'Atomic Habits',
            'The Subtle Art of Not Giving a F*ck',
            'You Are a Badass',
            'The Life-Changing Magic of Tidying Up',
            'The 7 Habits of Highly Effective People',
            'How to Win Friends and Influence People',
            'Rich Dad Poor Dad',
            'The Four Agreements',
            'The Alchemist',
            'The Secret',
            'The Road Less Traveled',
            'Daring Greatly',
            'The Gifts of Imperfection',
            'Drive',
            'Mindset',
            'Start with Why',
            'Leaders Eat Last',
            'The Lean Startup',
            'Zero to One',
            'The Hard Thing About Hard Things',
            'Good to Great',
            'The Innovator\'s Dilemma',
            'The Art of War',
            'The Prince',
            'Meditations',
            'The Power of Now',
            'A New Earth',
            'The Untethered Soul',
            'The Book of Joy',
            'The Happiness Project',
            'The Art of Happiness',
            'The Road to Character',
            'The Wisdom of Sundays',
            'The Purpose Driven Life',
            'The Shack',
            'Heaven is for Real',
            'Proof of Heaven',
            '90 Minutes in Heaven',
            'The Case for Christ',
            'Mere Christianity',
            'The Screwtape Letters',
            'The Problem of Pain',
            'The Great Divorce',
            'A Grief Observed',
            'Surprised by Joy',
            'The Ragamuffin Gospel',
            'Blue Like Jazz',
            'Love Wins',
            'Crazy Love',
            'Radical',
            'Forgotten God',
            'The Purpose of Christmas',
            'The Reason for God',
            'The Case for Faith',
            'The Case for a Creator',
            'The Case for Grace',
            'The Case for Miracles',
            'The Case for Hope',
            'The Case for Heaven',
            'The Case for Easter',
            'The Case for Christmas',
            'The Case for the Real Jesus',
            'The Case for the Resurrection',
            'The Case for the Psalms',
            'The Case for the Virgin Birth',
            'The Case for the Bible',
            'The Case for the Holy Spirit',
            'The Case for the Trinity',
            'The Case for the Deity of Christ',
            'The Case for the Gospel',
            'The Case for the Cross',
            'The Case for the Second Coming',
            'The Case for the End Times',
            'The Case for the Millennium',
            'The Case for the Rapture',
            'The Case for the Antichrist',
            'The Case for the Mark of the Beast',
            'The Case for the 144,000',
            'The Case for the Two Witnesses',
            'The Case for the New Jerusalem',
            'The Case for the New Heaven and New Earth',
            'The Case for the Tree of Life',
            'The Case for the River of Life',
            'The Case for the Book of Life',
            'The Case for the Lamb\'s Book of Life',
            'The Case for the Book of Revelation',
            'The Case for the Book of Daniel',
            'The Case for the Book of Ezekiel',
            'The Case for the Book of Isaiah',
            'The Case for the Book of Jeremiah',
            'The Case for the Book of Lamentations',
            'The Case for the Book of Hosea',
            'The Case for the Book of Joel',
            'The Case for the Book of Amos',
            'The Case for the Book of Obadiah',
            'The Case for the Book of Jonah',
            'The Case for the Book of Micah',
            'The Case for the Book of Nahum',
            'The Case for the Book of Habakkuk',
            'The Case for the Book of Zephaniah',
            'The Case for the Book of Haggai',
            'The Case for the Book of Zechariah',
            'The Case for the Book of Malachi',
        ];
        return [
            'title' => $this->faker->unique()->randomElement($fantasyTitles),
            'author_id' => Author::factory(),
            'category_id' => Category::factory(),
            'status' => $this->faker->randomElement(['available', 'borrowed']),
        ];
    }
} 